name: nestcare
description: "A household care and maintenance app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  responsive_sizer: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: DankMono
      fonts:
        - asset: assets/fonts/DankMono-Regular.otf
        - asset: assets/fonts/DankMono-Italic.otf
          style: italic
        - asset: assets/fonts/DankMono-Bold.otf
          weight: 700

